# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d52b0838364c5d54ef20805cef3696b72f284da9520f8ec9d264b97b11fc6d9469bfbc3e4fbc292a315982dee7d6dbcd5e3a0f2d8381547bf0a786a766c59ae7

test:
  secret_key_base: 4f5a0a34e31650ac633e0fad7c5da7f45f95028ae458ef94b00b5bffd4030fffc4b640e7323488869352e4ef7863adfc891b609944ad4b9149b5cb4e305d60d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
